views:    
  - title: Controles    
    header: {}
    background:
      opacity: 30
      alignment: center
      size: cover
      repeat: repeat
      attachment: scroll
    type: sections
    icon: mdi:home
    cards: []
    path: controls
    max_columns: 4
    theme: minimalist-desktop
    top_margin: false
    sections:
      - name: luces
        type: grid
        cards:
          - type: heading
            show_icon: false
            heading: Luces
            heading_style: title
          - name: luz-comedor
            type: grid
            columns: 1
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.comedor
                show_icon: true
                icon: mdi:sofa
                color: >
                  [[[ return states['vacuum.jaime'].state
                  !== 'docked' ? 'rgb(82, 45, 128)' : 'grey'; ]]]
              - type: grid
                columns: 3
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,214,170)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.comedor
                      data:
                        rgb_color:
                          - 255
                          - 214
                          - 170
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.comedor
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-off
                    color_type: icon
                    color: rgb(128,128,128)
                    tap_action:
                      action: call-service
                      service: light.turn_off
                      target:
                        entity_id: light.comedor
          - name: luz-dormitorio
            type: grid
            columns: 1
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.dormitorio
                show_icon: true
                icon: mdi:bed
                card_mod:
                  style: |
                    .icon {
                      display: none !important;
                    }
              - type: grid
                columns: 3
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,214,170)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.dormitorio
                      data:
                        rgb_color:
                          - 255
                          - 214
                          - 170
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.dormitorio
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-off
                    color_type: icon
                    color: rgb(128,128,128)
                    tap_action:
                      action: call-service
                      service: light.turn_off
                      target:
                        entity_id: light.dormitorio
          - name: luz-escritorio
            type: grid
            columns: 1
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.escritorio
                show_icon: true
                icon: mdi:chair-rolling
                card_mod:
                  style: |
                    .icon {
                      display: none !important;
                    }
              - type: grid
                columns: 3
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,214,170)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.escritorio
                      data:
                        rgb_color:
                          - 255
                          - 214
                          - 170
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.escritorio
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-off
                    color_type: icon
                    color: rgb(128,128,128)
                    tap_action:
                      action: call-service
                      service: light.turn_off
                      target:
                        entity_id: light.escritorio
 