views:
  - title: Controles
    header: {}
    background:
      opacity: 30
      alignment: center
      size: cover
      repeat: repeat
      attachment: scroll
    type: sections
    icon: mdi:home
    cards: []
    path: controls
    max_columns: 4
    theme: minimalist-desktop
    top_margin: false
    sections:
      - name: luces
        type: grid
        cards:
          - type: heading
            show_icon: false
            heading: ''
            heading_style: title
            card_mod:
              style: |
                ha-card {
                  color: rgb(120,100,100);             /* Text color */
                  font-weight: 800;           /* Bold */
                  font-size: 1.5rem;          /* Text size */
                  text-align: center;         /* Center the text */
                  text-transform: uppercase;  /* Optional: make all caps */
                  padding: 8px 0;
                }
          - name: luz-comedor
            type: grid
            columns: 2
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.comedor
                show_icon: true
                icon: mdi:sofa
              - type: grid
                columns: 2
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(250, 220, 167)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.comedor
                      data:
                        brightness: 255
                        color_temp: 284
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.comedor
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
          - name: luz-dormitorio
            type: grid
            columns: 2
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.dormitorio
                show_icon: true
                icon: mdi:bed
              - type: grid
                columns: 2
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(250, 220, 167)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.dormitorio
                      data:
                        brightness: 255
                        color_temp: 284
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.dormitorio
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
          - name: luz-escritorio
            type: grid
            columns: 2
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.escritorio
                show_icon: false
                icon: mdi:chair-rolling
              - type: grid
                columns: 2
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(250, 220, 167)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.escritorio
                      data:
                        brightness: 255
                        color_temp: 284
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb
                    color_type: icon
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.escritorio
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
          - name: luz-todas
            type: grid
            columns: 1
            square: false
            cards:
              - type: custom:big-slider-card
                entity: light.todas
                show_icon: true
                icon: mdi:home
              - type: grid
                columns: 5
                square: false
                cards:
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-multiple
                    color: rgb(250, 220, 167)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.todas
                      data:
                        brightness: 255
                        color_temp: 284
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-multiple
                    color: rgb(255,255,255)
                    tap_action:
                      action: call-service
                      service: light.turn_on
                      target:
                        entity_id: light.todas
                      data:
                        rgb_color:
                          - 255
                          - 255
                          - 255
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-multiple-off
                    color_type: icon
                    color: grey
                    tap_action:
                      action: call-service
                      service: light.turn_off
                      target:
                        entity_id: light.todas
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-multiple
                    color_type: icon
                    styles:
                      card:
                        - background: linear-gradient(45deg, rgb(255,0,1), rgb(225,225,0))
                    tap_action:
                      action: call-service
                      service: hue.activate_scene
                      target:
                        entity_id: scene.todas_honolulu
                  - type: custom:button-card
                    section_mode: true
                    icon: mdi:lightbulb-multiple
                    color_type: icon
                    styles:
                      card:
                        - background: >-
                            linear-gradient(45deg, rgb(188,255,110),
                            rgb(1,2,122))
                    tap_action:
                      action: call-service
                      service: hue.activate_scene
                      target:
                        entity_id: scene.todas_aurora_boreal
      - name: aspiradora
        type: grid
        cards:
          - type: heading
            heading_style: title
            card_mod:
              style: |
                ha-card {
                  color: rgb(120,100,100);             /* Text color */
                  font-weight: 800;           /* Bold */
                  font-size: 1.5rem;          /* Text size */
                  text-align: center;         /* Center the text */
                  text-transform: uppercase;  /* Optional: make all caps */
                  padding: 8px 0;
                }
          - square: false
            type: grid
            columns: 2
            cards:
              - show_name: true
                show_icon: true
                content: |
                  "sdadsadsa"
                icon: >
                  [[[ return states['vacuum.jaime'].state ===  'docked'  ?
                  'mdi:robot-vacuum'  : 'mdi:home-import-outline'; ]]]
                color_style: icon
                color: rgb(82, 45, 128)
                type: custom:button-card
                tap_action:
                  action: call-service
                  service: >
                    [[[ return states['vacuum.jaime'].state === 'docked'  ?
                    'vacuum.start' : 'vacuum.return_to_base'; ]]]
                  target:
                    entity_id: vacuum.jaime
                square: false
              - square: false
                type: grid
                cards:
                  - type: custom:button-card
                    icon: mdi:sofa
                    color_style: icon
                    color: rgb(82, 45, 128)
                    tap_action:
                      action: call-service
                      service: sharkiq.clean_room
                      data:
                        rooms:
                          - comedor
                      target:
                        entity_id: vacuum.jaime
                  - type: custom:button-card
                    icon: mdi:bed
                    color_style: icon
                    color: rgb(82, 45, 128)
                    tap_action:
                      action: call-service
                      service: sharkiq.clean_room
                      data:
                        rooms:
                          - dormitorio
                      target:
                        entity_id: vacuum.jaime
                  - type: custom:button-card
                    icon: mdi:chair-rolling
                    color_style: icon
                    color: rgb(82, 45, 128)
                    tap_action:
                      action: call-service
                      service: sharkiq.clean_room
                      data:
                        rooms:
                          - escritorio
                      target:
                        entity_id: vacuum.jaime
                  - type: custom:button-card
                    icon: mdi:faucet-variant
                    color_style: icon
                    color: rgb(82, 45, 128)
                    tap_action:
                      action: call-service
                      service: sharkiq.clean_room
                      data:
                        rooms:
                          - cocina
                      target:
                        entity_id: vacuum.jaime
                columns: 2
          - name: intensidad
            square: false
            type: grid
            cards:
              - show_name: false
                show_icon: true
                icon: mdi:numeric-1
                color_style: icon
                type: custom:button-card
                tap_action:
                  action: call-service
                  service: vacuum.set_fan_speed
                  target:
                    entity_id: vacuum.jaime
                  data:
                    fan_speed: eco
                styles:
                  icon:
                    - color: >
                        [[[ return states['vacuum.jaime'].attributes.fan_speed
                        === 'Eco' ? 'grey' : 'rgb(82, 45, 128)' ; ]]]
              - show_name: false
                show_icon: true
                color_style: icon
                color: rgb(82, 45, 128)
                type: custom:button-card
                styles:
                  icon:
                    - color: >
                        [[[ return states['vacuum.jaime'].attributes.fan_speed
                        === 'Normal' ? 'grey' : 'rgb(82, 45, 128)' ; ]]]
                tap_action:
                  action: call-service
                  service: vacuum.set_fan_speed
                  target:
                    entity_id: vacuum.jaime
                  data:
                    fan_speed: normal
                icon: mdi:numeric-2
              - show_name: false
                show_icon: true
                color_style: icon
                color: rgb(123, 68, 192)
                type: custom:button-card
                styles:
                  icon:
                    - color: >
                        [[[ return states['vacuum.jaime'].attributes.fan_speed
                        === 'Max' ? 'grey' : 'rgb(82, 45, 128)' ; ]]]
                tap_action:
                  action: call-service
                  service: vacuum.set_fan_speed
                  target:
                    entity_id: vacuum.jaime
                  data:
                    fan_speed: max
                icon: mdi:numeric-3
            columns: 3
